spring.application.name=family-tree

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/familytree}
spring.datasource.username=${DB_USER:familyuser}
spring.datasource.password=${DB_PASSWORD:familysecret}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

flyway.enabled=true
flyway.locations=classpath:db/migration

server.port=8080
