spring.application.name=family-tree

spring.datasource.url=jdbc:postgresql://db:5432/familytree
spring.datasource.username=familyuser
spring.datasource.password=familysecret
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

flyway.enabled=true
flyway.locations=classpath:db/migration

server.port=8080
