spring.application.name=family-tree

spring.datasource.url=jdbc:postgresql://db:5432/familytree
spring.datasource.username=familyuser
spring.datasource.password=familysecret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
